version: 2

builds:
  - main: ./cmd/littlefactory
    binary: littlefactory
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: gbrindisi
    name: littlefactory
